#!/usr/bin/env python
import os
import webbrowser, threading

os.chdir(os.path.split(__file__)[0])

from app import app

url = "http://127.0.0.1:5000"

threading.Timer(1.25, lambda:webbrowser.open(url)).start()
app.run(debug=True)