#!/usr/bin/env python
import os, time
from threading import Thread
import subprocess

os.chdir('/Users/adriengomar/Documents/PERSONAL/WEB_APP/WONEY/')

from app import app

thread = Thread(target=app.run)
thread.start()
time.sleep(10)
subprocess.call(['/Applications/node-webkit.app/Contents/MacOS/node-webkit', 'package.nw'])